Story9/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings

app_name = 'Story9'

urlpatterns = [
    path('', views.home, name="home"),
    path('searchbook', views.home, name="home"),
    path('searchJson', views.searchJson, name="searchJson"),
    path('increasefav', views.increasefav, name='increasefav'),
    path('decreasefav', views.decreasefav, name='decreasefav'),
    path('logout', views.logout_view , name='logout'),

]

StoryTDD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Story9.urls')),
    path('auth/', include('social_django.urls', namespace='social'))
]

Story9/models.py
from django.db import models

Story9/forms.py
from django import forms

Story9/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
import json
import requests
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout


def logout_view(request):
    request.session.flush()
    logout(request)
    return HttpResponseRedirect('/searchbook')

def home(request):
    if request.user.is_authenticated:
        request.session['user'] = request.user.username
        request.session['email'] = request.user.email
        count = request.session.get('counter', 0)
        request.session['counter'] = count + 1
        for key, value in request.session.items():
            print('{} = {}'.format(key, value))
    return render(request, 'book.html')

def increasefav(request):
    print(dict(request.session))
    request.session['counter'] = request.session['counter'] + 1
    return HttpResponse(request.session['counter'], content_type='application/json')

def decreasefav(request):
    #print(dict(request.session))
    request.session['counter'] = request.session['counter'] - 1
    return HttpResponse(request.session['counter'], content_type='application/json')

def searchJson(request):
    searching =  request.GET.get('cari')
    url = "https://www.googleapis.com/books/v1/volumes?q=" + searching
    data = requests.get(url).json()
    if request.user.is_authenticated:
        count = request.session.get('counter',0)
        request.session['counter'] = count
        for key, value in request.session.items():
            print('{} => {}'.format(key,value))
    return JsonResponse(data)

Story9/templates/book.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="id">
<head>
  <title>List of Books</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/mycss.css' %}">
  <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
  <meta name="google-signin-client_id" content="507958782827-2km1po0hp3ggoru9fsemrg84tns6bbdv.apps.googleusercontent.com">
  <script src="https://apis.google.com/js/platform.js" async defer></script>

  <style type="text/css">
		body{
			background: #23F4CE;
		}
		#myInput{
		  	background-position: right;
		  	background-repeat: no-repeat;
		  	width: 30%;
		  	font-size: 16px;
		  	padding: 12px 20px 12px 40px;
		  	border: 1px solid #ddd;
		  	margin-bottom: 12px;
		}

  </style>
</head>
<body>
<div class="jumbotron">
   <center>
     <h1 class="ml9">
      <span class="text-wrapper">
        <span class="letters">List of Books</span>
      </span>
     </h1>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
   </center>
</div>

<div class="row" style="margin-top: 3%">
  {%if user.is_authenticated%}
  <header class = "m-3" ">
  <a href= "{% url 'Story9:logout'%}" style="text-transform:none; margin-top: 3%;">
    <div class="left">
      <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
    </div>
    Log Out
  </a>
  <h3>Hello, {{ user.username }}!</h3>
  </header>
  {%else%}<header>
  <a href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none">
    <div class="left">
      <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
    </div>
    Login with Google
  </a>
  <br>
</header>
  {%endif%}
</div>

<!--<div class="text-center" style="padding-top: 2%;">-->
  <!--<input id="myInput" type="text" placeholder="Search your books here...">-->
<!--</div>-->
<!--<script>-->
		<!--$(document).ready(function(){-->
		  <!--$("#myInput").on("keyup", function() {-->
		    <!--var value = $(this).val().toLowerCase();-->
		    <!--$("#myTable tr").filter(function() {-->
		      <!--$(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)-->
		    <!--});-->
		  <!--});-->
		<!--});-->
<!--</script>-->


<header class="text-center">
  <div class="container1">
    <center>
      <h4 id="fav"><i class='fa fa-star'style = 'color : #DA70D6'></i> {{ count }} </h4>
    </center>
  </div>
  <h4 style="color: white;">Favorites</h4>
</header>
<center>
  <input id = "searchbar" placeholder="  type the name of the book" style="min-width: 250px;align-content: center">
  <button type="button" class="btn btn-info" id ="caribtn" onclick="cari()" style ="align-content: center">Search</button>
</center>
<div style="padding-top: 2%; margin-left: 10%;margin-right: 10%;">
  <table id="result" class="table table-striped table-light table-bordered table-hover">
    <thead class="thead-light">
    <tr>
      <th scope="col" style="text-align: center;">No</th>
      <th scope="col" style="text-align: center;">Cover</th>
      <th scope="col" style="text-align: center;">Title</th>
      <th scope="col" style="text-align: center;">Authors</th>
      <th scope="col" style="text-align: center;">Publisher</th>
      <th scope="col" style="text-align: center;">Published Date</th>
      <th scope="col" style="text-align: center;">Categories</th>
      <th scope="col" style="text-align: center;">Add to Favorites</th>
    </tr>
    </thead>
    <tbody id='myTable'>
    </tbody>
  </table>

</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script src="{% static 'js/myjs.js' %}"></script>
</body>
</html>